### ISSUE TITLE
fails trying to copy gitignore

### ISSUE THREAD

**Issue by connaryscott** [ACloudGuru/generator-serverless-service#3]
```
C02PQ6FEG3QD:v1 chscott$ yo serverless-service:aws-nodejs
? Your service name my-nodejs-service
? AWS Profile Name? infra
? AWS Region? us-east-1
? AWS Account Id? **REDACTED**
? Would you like to install snyk to detect package vulnerabilities? No
? Would you like to install mocha, chai, sinon and istanbul for testing? No
? Would you like to install eslint for linting? No

events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/generators/aws-nodejs/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at null.<anonymous> (/Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/generators/aws-nodejs/index.js:176:15)
    at Array.forEach (native)
    at module.exports.generators.Base.extend.writing (/Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/generators/aws-nodejs/index.js:175:15)
    at Object.<anonymous> (/Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/node_modules/run-async/index.js:26:25
    at /Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/node_modules/run-async/index.js:25:19
    at /Users/chscott/.nvm_serverless_1/versions/node/v5.12.0/lib/node_modules/generator-serverless-service/node_modules/yeoman-generator/lib/base.js:432:9
    at tryOnImmediate (timers.js:534:15)
```

**Comment by johncmckim** [comment]
Thanks for reporting this. The project is very new, glad to get any feedback you have. I'm adding a fix to the issue now.

**Comment by johncmckim** [comment]
Just released a fix. Would love to get your feedback if you have any.
